# Generated by Django 5.1.6 on 2025-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0002_dummy_lname"),
    ]

    operations = [
        migrations.CreateModel(
            name="faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("que", models.TextField()),
                ("ans", models.TextField()),
            ],
        ),
    ]
