# Generated by Django 5.1.6 on 2025-02-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0003_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_name",
                    models.CharField(max_length=155, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "Title",
                    models.CharField(max_length=155, primary_key=True, serialize=False),
                ),
                ("Company", models.CharField(max_length=155)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("image", models.ImageField(blank=True, upload_to="data")),
                ("description", models.TextField()),
                (
                    "category_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecomapp.category",
                    ),
                ),
            ],
        ),
    ]
