# Generated by Django 5.1.6 on 2025-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0004_category_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mycontact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("phone_no", models.CharField(max_length=15)),
            ],
        ),
    ]
