# Generated by Django 5.1.6 on 2025-03-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0006_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="address",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="house_flat_no",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="landmark",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="phone_no",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="pincode",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
