# Generated by Django 5.1.6 on 2025-03-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0007_register_address_register_house_flat_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="house_flat_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="landmark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="phone_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
