# Generated by Django 5.1.6 on 2025-03-04 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ecomapp",
            "0008_alter_register_address_alter_register_house_flat_no_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Register",
            new_name="Register1",
        ),
    ]
