# Generated by Django 5.1.6 on 2025-03-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0009_rename_register_register1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="data"),
        ),
    ]
