# Generated by Django 5.1.6 on 2025-03-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0012_payment_orderitem_shippingaddress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="cart",
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("Success", "Success"), ("Failed", "Failed")], max_length=20
            ),
        ),
    ]
