# Generated by Django 5.1.6 on 2025-03-26 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0013_remove_payment_cart_alter_payment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
