# Generated by Django 5.1.4 on 2025-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0015_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register1",
            name="house_flat_no",
        ),
        migrations.RemoveField(
            model_name="register1",
            name="phone_no",
        ),
        migrations.AddField(
            model_name="register1",
            name="house_flat",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="register1",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="register1",
            name="address",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="register1",
            name="landmark",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="register1",
            name="pincode",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
