# Generated by Django 5.1.4 on 2025-04-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0016_remove_register1_house_flat_no_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="register1",
            old_name="house_flat",
            new_name="house_flat_no",
        ),
        migrations.RenameField(
            model_name="register1",
            old_name="phone",
            new_name="phone_no",
        ),
    ]
